// Generated by CoffeeScript 1.12.7
(function() {
  var AutoHide, m, u,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  m = require('mithril');

  u = require('./utils');

  AutoHide = (function() {
    function AutoHide(arg) {
      var ref;
      this.widget = arg.widget, this.onHide = (ref = arg.onHide) != null ? ref : u.noOp;
      this.hide = bind(this.hide, this);
      this.show = bind(this.show, this);
      this.showing = false;
    }

    AutoHide.prototype.onHideInternal = function(elem) {
      return (function(_this) {
        return function(e) {
          if (!elem.contains(e.target)) {
            _this.showing = false;
          }
          m.redraw();
          _this.onHide();
          return true;
        };
      })(this);
    };

    AutoHide.prototype.show = function() {
      return this.showing = true;
    };

    AutoHide.prototype.hide = function() {
      this.showing = false;
      return this.onHide();
    };

    AutoHide.prototype.view = function() {
      var self;
      self = this;
      return m('.HideOnBlur', {
        oncreate: function(vnode) {
          return window.addEventListener('click', self.onHideInternal(vnode.dom), true);
        },
        onremove: function(vnode) {
          return window.removeEventListener('click', self.onHideInternal(vnode.dom), true);
        }
      }, this.showing ? this.widget.view() : void 0);
    };

    return AutoHide;

  })();

  module.exports = AutoHide;

}).call(this);
