// Generated by CoffeeScript 1.12.7
(function() {
  var CHECK_SVG, CheckBox, HYPHEN_SVG, m, ref, s, u,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  m = require('mithril');

  s = require('mss-js');

  u = require('./utils');

  ref = require('./CONSTANT'), CHECK_SVG = ref.CHECK_SVG, HYPHEN_SVG = ref.HYPHEN_SVG;

  CheckBox = (function() {
    function CheckBox(arg) {
      var ref1, ref2, ref3, ref4, ref5;
      this.checked = (ref1 = arg.checked) != null ? ref1 : true, this.label = (ref2 = arg.label) != null ? ref2 : 'foo', this.disabled = (ref3 = arg.disabled) != null ? ref3 : false, this.partial = (ref4 = arg.partial) != null ? ref4 : false, this.onToggle = (ref5 = arg.onToggle) != null ? ref5 : u.noOp;
      this.onToggleInternal = bind(this.onToggleInternal, this);
    }

    CheckBox.prototype.onToggleInternal = function(e) {
      this.checked = !this.checked;
      return this.onToggle(this.selected, e);
    };

    CheckBox.prototype.view = function() {
      return m('label.CheckBox', m('input', {
        onchange: this.onToggleInternal,
        type: 'checkbox',
        checked: this.checked,
        disabled: this.disabled
      }), m('.CheckMark', this.checked ? (this.partial ? m.trust(HYPHEN_SVG) : m.trust(CHECK_SVG)) : void 0), m('.CheckLabel', this.label));
    };

    return CheckBox;

  })();

  CheckBox.mss = {
    CheckBox: {
      display: 'inline-block',
      verticalAlign: 'middle',
      cursor: 'pointer',
      input: {
        display: 'none'
      },
      verticalAlign: 'middle',
      userSelect: 'none',
      CheckMark: {
        display: 'inline-block',
        height: '16px',
        width: '16px',
        boxSizing: 'border-box',
        borderRadius: '2px',
        verticalAlign: 'middle',
        border: '1px solid #2F88FF',
        background: 'none',
        svg: {
          width: '10px',
          height: '10px',
          margin: '2px',
          fill: '#FFF'
        }
      },
      CheckLabel: {
        display: 'inline-block',
        marginLeft: '8px',
        color: '#333'
      },
      'input:disabled ~ .CheckLabel': {
        color: '#D6D6D6'
      },
      'input:disabled ~ .CheckMark': {
        background: '#FCFCFC',
        border: '1px solid #EDF1F5'
      },
      'input:checked ~ .CheckMark': {
        background: '#2F88FF',
        svg: {
          fill: '#fff'
        }
      },
      'input:disabled:checked ~ .CheckMark': {
        background: '#A8D7FF',
        border: '1px solid #A8D7FF',
        svg: {
          fill: '#fff'
        }
      }
    }
  };

  module.exports = CheckBox;

}).call(this);
