// Generated by CoffeeScript 1.12.7
(function() {
  var COLLASPE_ARROW, Collaspe, m, s, u,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  m = require('mithril');

  s = require('mss-js');

  u = require('./utils');

  COLLASPE_ARROW = require('./CONSTANT').COLLASPE_ARROW;

  Collaspe = (function() {
    function Collaspe(arg) {
      var _, ref, ref1, ref2, ref3, ref4, ref5, ref6, ref7;
      this.titleArray = (ref = arg.titleArray) != null ? ref : [], this.widgetArray = (ref1 = arg.widgetArray) != null ? ref1 : [], this.stateArray = (ref2 = arg.stateArray) != null ? ref2 : (function() {
        var k, len, ref3, results;
        ref3 = this.widgetArray;
        results = [];
        for (k = 0, len = ref3.length; k < len; k++) {
          _ = ref3[k];
          results.push(false);
        }
        return results;
      }).call(this), this.autoCollaspe = (ref3 = arg.autoCollaspe) != null ? ref3 : true, this.iconType = (ref4 = arg.iconType) != null ? ref4 : 'RIGHT', this.borderType = (ref5 = arg.borderType) != null ? ref5 : 'ALL', this.onExpand = (ref6 = arg.onExpand) != null ? ref6 : u.noOp, this.onCollaspe = (ref7 = arg.onCollaspe) != null ? ref7 : u.noOp;
      this.onCollapseInternal = bind(this.onCollapseInternal, this);
    }

    Collaspe.prototype.onCollapseInternal = function(e) {
      var i, j, k, len, ref;
      i = parseInt(u.getCurrentTargetData(e, 'index'));
      if (this.autoCollaspe) {
        ref = this.stateArray;
        for (j = k = 0, len = ref.length; k < len; j = ++k) {
          s = ref[j];
          if (s) {
            if (i !== j) {
              this.onCollaspe(j, e);
              this.stateArray[j] = false;
            }
          }
        }
      }
      if (this.stateArray[i] === false) {
        this.stateArray[i] = true;
        return this.onExpand(i, e);
      } else {
        this.stateArray[i] = false;
        return this.onCollaspe(i, e);
      }
    };

    Collaspe.prototype.view = function() {
      var expanded, i, self, title;
      self = this;
      return m('.Collaspe', {
        style: {
          borderWidth: this.borderType === 'NONE' ? '0' : this.borderType === 'ALL' ? '1px 1px 0 1px' : '1px 0 0 0',
          borderRadius: this.borderType === 'ALL' ? '4px' : 0
        }
      }, (function() {
        var k, len, ref, results;
        ref = this.titleArray;
        results = [];
        for (i = k = 0, len = ref.length; k < len; i = ++k) {
          title = ref[i];
          expanded = this.stateArray[i];
          results.push(m('.CollaspeGroup', {
            key: i,
            className: expanded ? 'Expanded' : ''
          }, m('.CollaspeTitle', {
            'data-index': i,
            onclick: this.onCollapseInternal
          }, m('span.Icon', {
            className: [this.iconType, expanded ? 'Expanded' : ''].join(' ')
          }, m.trust(COLLASPE_ARROW)), m('span.Title', title)), m('.CollaspeBody', {
            style: {
              borderWidth: this.borderType === 'NONE' ? '0' : this.borderType === 'ALL' && expanded ? '1px 0 1px 0' : '0 0 1px 0'
            },
            className: expanded ? 'Expanded' : ''
          }, expanded ? this.widgetArray[i] : void 0)));
        }
        return results;
      }).call(this));
    };

    return Collaspe;

  })();

  Collaspe.mss = {
    Collaspe: {
      boxSizing: 'border-box',
      borderStyle: 'solid',
      borderColor: '#DADFE3',
      overflow: 'hidden',
      CollaspeTitle: {
        color: '#333',
        lineHeight: '32px',
        height: '32px',
        $hover: {
          cursor: 'pointer'
        },
        Title: {
          verticalAlign: 'middle',
          marginLeft: '16px'
        },
        Icon: {
          margin: '11px 10px'
        },
        svg: {
          fill: '#666',
          width: '16px',
          verticalAlign: 'middle',
          transform: 'rotateZ(180deg)',
          transition: 'all 0.3s'
        },
        LEFT: {
          marginRight: '-10px',
          float: 'left',
          svg: {
            transform: 'rotateZ(-90deg)'
          }
        },
        RIGHT: {
          float: 'right'
        },
        '.LEFT.Expanded': {
          svg: {
            transform: 'rotateZ(0)'
          }
        },
        '.RIGHT.Expanded': {
          svg: {
            transform: 'rotateZ(0)'
          }
        }
      },
      CollaspeBody: {
        borderStyle: 'solid',
        borderColor: '#DADFE3'
      },
      '.CollaspeBody.Expanded': {
        padding: '16px 32px'
      }
    }
  };

  module.exports = Collaspe;

}).call(this);
