// Generated by CoffeeScript 1.12.7
(function() {
  var AutoHide, CALENDAR, DatePicker, DateRange, m, s, u,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  m = require('mithril');

  s = require('mss-js');

  u = require('./utils');

  AutoHide = require('./AutoHide');

  DatePicker = require('./DatePicker');

  CALENDAR = require('./CONSTANT').CALENDAR;

  DateRange = (function() {
    function DateRange(arg) {
      var endDate, ref, ref1, ref2, startDate;
      startDate = arg.startDate, endDate = arg.endDate, this.ifStartDateAvailable = (ref = arg.ifStartDateAvailable) != null ? ref : (function() {
        return true;
      }), this.ifEndDateAvailable = (ref1 = arg.ifEndDateAvailable) != null ? ref1 : (function() {
        return true;
      }), this.onSelect = (ref2 = arg.onSelect) != null ? ref2 : u.noOp;
      this.onSelectInternal = bind(this.onSelectInternal, this);
      if (startDate) {
        this.startDate = u.clearDateHMS(new Date(startDate));
      }
      if (endDate) {
        this.endDate = u.clearDateHMS(new Date(endDate));
      }
      this.startDatePicker = new DatePicker({
        date: startDate,
        ifDateAvailable: this.ifStartDateAvailable,
        onSelect: this.onSelectInternal
      });
      this.endDatePicker = new DatePicker({
        date: endDate,
        ifDateAvailable: this.ifEndDateAvailable,
        onSelect: this.onSelectInternal
      });
      this.datePickerWrapper = new AutoHide({
        widget: {
          view: (function(_this) {
            return function() {
              return m('.DateWrapper', _this.startDatePicker.autoHideDatePicker.widget.view(), m('.DateEndWrapper', _this.endDatePicker.autoHideDatePicker.widget.view()));
            };
          })(this)
        }
      });
      if ((this.startDate != null) && (this.endDate != null)) {
        this.startDatePicker.highlightStartDate = this.endDatePicker.highlightStartDate = this.startDate;
        this.startDatePicker.highlightEndDate = this.endDatePicker.highlightEndDate = this.endDate;
      }
    }

    DateRange.prototype.onSelectInternal = function(d) {
      if ((this.startDate != null) && (this.endDate != null)) {
        this.startDatePicker.highlightStartDate = this.endDatePicker.highlightStartDate = null;
        this.startDatePicker.highlightEndDate = this.endDatePicker.highlightEndDate = null;
        this.startDate = new Date(d);
        this.endDate = null;
      } else if ((this.startDate != null) && d.getTime() > this.startDate.getTime()) {
        this.endDate = new Date(d);
      } else if ((this.startDate != null) && d.getTime() < this.startDate.getTime()) {
        this.endDate = this.startDate;
        this.startDate = new Date(d);
      } else {
        this.startDate = new Date(d);
      }
      if ((this.startDate != null) && (this.endDate != null)) {
        this.startDatePicker.highlightStartDate = this.endDatePicker.highlightStartDate = this.startDate;
        this.startDatePicker.highlightEndDate = this.endDatePicker.highlightEndDate = this.endDate;
        this.startDatePicker.date = null;
        this.endDatePicker.date = null;
        return this.onSelect(this.startDate, this.endDate);
      }
    };

    DateRange.prototype.view = function() {
      return m('.DatePicker.DateRange', m('.DateLabel', {
        onclick: (function(_this) {
          return function() {
            return _this.datePickerWrapper.show();
          };
        })(this),
        className: !((this.startDate != null) && (this.endDate != null)) ? 'Note' : ''
      }, (this.startDate != null) && (this.endDate != null) ? (u.formatDate(this.startDate)) + " ~ " + (u.formatDate(this.endDate)) : '请选择日期范围'), m('.DateIcon', m.trust(CALENDAR)), this.datePickerWrapper.view());
    };

    return DateRange;

  })();

  DateRange.mss = s.merge([
    DatePicker.mss, {
      DateRange: {
        DateWrapper: {
          position: 'absolute',
          width: '576px',
          height: '280px',
          top: '38px',
          left: 0,
          background: '#FFF',
          boxShadow: '0px 2px 6px 0px #00000014',
          borderRadius: '4px',
          zIndex: 1,
          DatePickerWidget: {
            top: 0,
            boxShadow: 'none'
          },
          DateEndWrapper: {
            DatePickerWidget: {
              left: '288px'
            }
          }
        }
      }
    }
  ]);

  module.exports = DateRange;

}).call(this);
